### ISSUE TITLE
[UX]No user facing feedback after clicking the submit button

### ISSUE THREAD

**Issue by chenliu0831** [aws-samples/sagemaker-studio-auto-shutdown-extension#1]
### Feature Request
After clicking the submit button, there's no feedback prompt or text of whether the time limit has been applied. Looks like there are something printed in the dev console, but it's not obvious to normal users.

**Desired behavior**: show a success/error message to user from UI

https://user-images.githubusercontent.com/1504463/103783518-d3e5a300-5006-11eb-8cd8-5e3f51b4bf3b.mp4

**Comment by rthamman** [comment]
Hi, Thanks for the feedback. We will be adding a confirmation message in the next release - end of April.

**Comment by garzoand** [comment]
This has been fixed now.
![image](https://user-images.githubusercontent.com/2110325/115638118-9a3f5c00-a2c6-11eb-80bd-17105a4cd669.png)
