### ISSUE TITLE
Extend idle checker to also check & delete idle Data Wrangler apps

### ISSUE THREAD

**Issue by TheissHe** [aws-samples/sagemaker-studio-auto-shutdown-extension#10]
Hey,

it would be nice to be able to to use the auto-shutdown-extension also for deleting idle Data Wrangler apps. Could this be included in the checker script?

Best,
Theiss

**Comment by rthamman** [comment]
Hi There, the extension does shutdown Data Wrangler apps after the idle time limit is reached. Please see this blog - https://aws.amazon.com/blogs/machine-learning/save-costs-by-automatically-shutting-down-idle-resources-within-amazon-sagemaker-studio/
