### ISSUE TITLE
Kernel sessions stucked in "pending" state does not get deleted

### ISSUE THREAD

**Issue by garzoand** [aws-samples/sagemaker-studio-auto-shutdown-extension#14]
The extension deletes session only which are in an 'idle' state. However, in some cases there are sessions which remains in a "pending" state. The extension will not remove these sessions, thus the instance will remain online if it has at least one pending session.

the extension should check the last_activity for pending sessions too and if it exceeds a certain timeout value, the session should be removed.

**Comment by garzoand** [comment]
{
  "datascience-1-0-ml-t3-medium-1abf3407f667f989be9d86559395": {
    "app": {
      "app_name": "datascience-1-0-ml-t3-medium-1abf3407f667f989be9d86559395",
      "environment_arn": "arn:aws:sagemaker:us-east-1:081325390199:image/datascience-1.0",
      "environment_name": "datascience-1.0",
      "image_name": "datascience-1.0",
      "instance_type": "ml.t3.medium",
      "lifecycle_config_arn": "None"
    },
    "sessions": [
      {
        "id": "f8c2a078-7cf7-4e3a-b0ea-200afae4eca4",
        "path": "Untitled.ipynb-2e4fd6a2-c2aa-4ace-ab85-15116e766798.ipynb",
        "name": "Untitled.ipynb",
        "type": "pending",
        "kernel": {
          "id": "7d04c50b-890d-49f2-b6db-5e6a4f83ca73",
          "name": "python3__SAGEMAKER_INTERNAL__arn:aws:sagemaker:us-east-1:081325390199:image/datascience-1.0",
          "last_activity": "2021-09-07T20:08:18.398669Z",
          "execution_state": "starting",
          "connections": 0,
          "instance_type": "ml.t3.medium",
          "app_name": "datascience-1-0-ml-t3-medium-1abf3407f667f989be9d86559395",
          "lifecycle_config_arn": "None"
        }
      }
    ],
    "terminals": []
  }
}

**Comment by rthamman** [comment]
An app when launched, goes into pending state and eventually to "In Service" state. In case there is an issue, app will be marked as failed. Customers are billed only when there is an active app. Shutting down pending apps will not be required. Closing this issue.
