### ISSUE TITLE
Edge case where Kernel is not shutting down

### ISSUE THREAD

**Issue by kadiy1k** [aws-samples/sagemaker-studio-auto-shutdown-extension#16]
We launched two notebooks with different kernels ( base python and data science ) with same instance type. Only data science notebook is actively used and we have not executed any cell in base python notebook. Once the idle time out is elapsed, the data science kernel gets terminated but base python kernel does not terminated until we execute a cell.

**Comment by rthamman** [comment]
Resolved. Kernels and Terminals have to be launched after the extension is installed. Using SageMaker Studio Lifecycle Configuration to install the extension is recommended as it will install when JupyterServer comes up.
