### ISSUE TITLE
This software is removed if I shutdown the Sagemaker Studio instance and then restart it

### ISSUE THREAD

**Issue by jagane-opensource** [aws-samples/sagemaker-studio-auto-shutdown-extension#2]
This software does not appear to survive a shutdown-restart cycle. The sidebar tool disappears and I need to run install_tarball.sh again. Is there a way to make it presistent?

**Comment by garzoand** [comment]
As the extension needs to be installed on top of a running Jupyter server container, currently there is no way to avoid the reinstallation after the restart of the "default" application. This is currently a limitation of SageMaker Studio and not the extension. However, hopefully we will be able to solve this issue soon either by adding this extension to the Jupyer server image directly or leverage some future Studio capabilities which would allow to install extensions "permanently".
