### ISSUE TITLE
Extension not working with JupyterLab 3

### ISSUE THREAD

**Issue by theminionn** [aws-samples/sagemaker-studio-auto-shutdown-extension#35]
Hello,

Attempting to install the auto shutdown extension on SageMaker Studio with JupyterLab 3 results in the following error:

Traceback (most recent call last):
  File "/home/sagemaker-user/.auto-shutdown/set-time-interval.sh", line 9, in <module>
    response = session.post("http://localhost:8888/jupyter/default/sagemaker-studio-autoshutdown/idle_checker", json={"idle_time": TIMEOUT, "keep_terminals": False}, params={"_xsrf": response.headers['Set-Cookie'].split(";")[0].split("=")[1]})
  File "/opt/conda/lib/python3.9/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]

Is this expected behaviour? I noticed the README now mentions that the extension supports versions < JupyterLab 2. Are there any plans to add support for JupyterLab 3 as it's now in public preview?

**Comment by durgasury** [comment]
Hi, the server extension does support JupyterLab 3.0. Can you share the full stack trace or the error message?

**Comment by theminionn** [comment]
Traceback (most recent call last):
  File "/home/sagemaker-user/.auto-shutdown/set-time-interval.sh", line 9, in <module>
    response = session.post("http://localhost:8888/jupyter/default/sagemaker-studio-autoshutdown/idle_checker", json={"idle_time": TIMEOUT, "keep_terminals": False}, params={"_xsrf": response.headers['Set-Cookie'].split(";")[0].split("=")[1]})
  File "/opt/conda/lib/python3.9/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]

**Comment by theminionn** [comment]
Closing this issue as we resolved it internally. I can confirm the extension works with JupyterLab 3. Thank you for your cooperation and assistance!
