### ISSUE TITLE
Pricing Issue for the JupyterServer app

### ISSUE THREAD

**Issue by yinsong-ph** [aws-samples/sagemaker-studio-auto-shutdown-extension#36]
Hi team,

I can see in your README.md page that

"Instance that hosts JupyterServer app and System Terminals is free"

But I found here https://docs.aws.amazon.com/sagemaker/latest/dg/notebooks-usage-metering.html it seems that the JupyterServer app is charged by its instance type.

Can you confirm if "Instance that hosts JupyterServer app and System Terminals is free" is still the case?

Thank you@

**Comment by durgasury** [comment]
Hi, 

The pricing is based on the KernelGateway instance type, not the JupyterServer (which hosts the Studio UI and allows user start to notebooks, image terminals etc.). I can confirm that as of today, the instance that hosts JupyterServer and System terminals is still free of charge.

The blog [here](https://aws.amazon.com/blogs/machine-learning/dive-deep-into-amazon-sagemaker-studio-notebook-architecture/) helps dive in to Studio architecture that's part of this repo's README. 

Closing this issue.
