### ISSUE TITLE
Jupyter Lab 3 extension support

### ISSUE THREAD

**Issue by franalgaba** [aws-samples/sagemaker-studio-auto-shutdown-extension#37]
Hi,

After the recent release of Jupyter Lab 3 in SageMaker Studio and now being the default and officially maintained version of Jupyter for Studio, we are planning to update all the Studio user profiles in our domains to use the new version. 

In our lifecycle configurations for Studio, we use this extension to handle the shutdown of Studio when not being used by users. After updating, Studio won't start due to the [incompatibility of this extension](https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension#option-2-jupyterlab-ui-and-server-side-extension) with the new Jupyter Lab version.

The error response from Studio is the following:

![Screenshot 2022-08-23 at 09 57 40](https://user-images.githubusercontent.com/24293857/186104573-7ee06bab-0650-41a0-86bc-8515f0ab8c99.png)

Is there going to be Jupyter Lab 3 support for this extension any time soon?
Thanks.

**Comment by durgasury** [comment]
Hi, are you using the server extension or the lab extension? The server extension is supported with Jupyter Lab 3 and is our [officially recommended version](https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension#option-1-jupyterlab-server-side-extension-recommended). Please try it out and let me know if you still face issues.

**Comment by Saahansen** [comment]
+1 on the error. 
We use LCC as well as part of a CDK workflow and have had the same issue since the update from JupyterLab 1 to 3.

**Comment by Saahansen** [comment]
@durgasury Thanks for the response. You were right, I had missed the update with the latest version but now everything works again. Thanks for your help!
