### ISSUE TITLE
Software is not working properly when we have specific IAM Policy 

### ISSUE THREAD

**Issue by Ghousecms** [aws-samples/sagemaker-studio-auto-shutdown-extension#4]
I have setup sagemaker studio and installed auto-shutdown extenction. it is not working properly.

**Comment by rthamman** [comment]
Hi, We are checking. Will circle back.

**Comment by JorritHimself** [comment]
Having the same issue. Maybe the IAM role issue identified in the other thread. Unsure.

What I do know is: it work fine some time ago. Does nothing currently.
I unistalled auto shutdown, stopped the jupyterserver, started a new studo session, reinstalled the auto-shutdown extension. 
Still no effect: idle apps keep running.

**Comment by rthamman** [comment]
Hi There, IAM permission has no implication on the extension. if you reinstalled the extension, please shutdown all your running kernels and start again. Let us know if you still run into issues and can coordinate a call.

**Comment by JorritHimself** [comment]
Okay. If it's not that than I dont understand why it stopped working recently. 

I'm also not terribly keen on trying to replicate what the issue was, but it did seemed to be solved by appending the AdministratorAccess to the user, then reinstalling.

**Comment by garzoand** [comment]
Hi, we also tried to replicate this issue, but we neither was able to. I am closing this one, however if you'll encounter with this again, please send us the console logs and feel free to reopen this issue. Thank you!
