### ISSUE TITLE
An error occurs when executing the set-time-interval.sh file

### ISSUE THREAD

**Issue by takuma-okada-1234** [aws-samples/sagemaker-studio-auto-shutdown-extension#41]
Hi!

I want to put automatic shutdown in SageMaker.

I tried following Option 1.2: Install the extension manually in README.md, but an error appears in 
the attached image.

I hope someone can give me a solution.

Also, I'm not good at English, so I would be very happy if you could reply in simple English.

![Location of occurrence](https://user-images.githubusercontent.com/104615284/192036405-aeb8e56a-b22b-43be-a547-ef7350f4d8af.png)
![terminal used](https://user-images.githubusercontent.com/104615284/192036651-8c58a307-0608-4f56-9559-618676784862.png)
![the error that occurred](https://user-images.githubusercontent.com/104615284/192036659-9dcf7c8c-fcf5-4b7c-832b-70cc1fb9f8aa.png)

**Comment by durgasury** [comment]
Hi, can you run `./set-time-interval.sh`, instead of `sh set-time-interval.sh`?

**Comment by takuma-okada-1234** [comment]
thank you for the advice

There is a difference between sh execution and ./ execution.

i didn't know

Thanks to you, I solved it!
