### ISSUE TITLE
auto-shutdown failing sometimes on some users

### ISSUE THREAD

**Issue by wdwatkins** [aws-samples/sagemaker-studio-auto-shutdown-extension#47]
I have seen several cases where for a particular Sagemaker user, the extension seems to not work and idle instances are left running for several days until we catch them through other means.  I would appreciate if you can provide any guidance for debugging.

We are running the server lifecycle script with no modifications, attached to our Sagemaker domain and the timeout set to 2 hours:
```
#!/bin/bash
# This script installs the idle notebook auto-checker server extension to SageMaker Studio
# The original extension has a lab extension part where users can set the idle timeout via a Jupyter Lab widget.
# In this version the script installs the server side of the extension only. The idle timeout
# can be set via a command-line script which will be also created by this create and places into the
# user's home folder
#
# Installing the server side extension does not require Internet connection (as all the dependencies are stored in the
# install tarball) and can be done via VPCOnly mode.

set -eux

# timeout in minutes
export TIMEOUT_IN_MINS=120

# Should already be running in user home directory, but just to check:
cd /home/sagemaker-user

# By working in a directory starting with ".", we won't clutter up users' Jupyter file tree views
mkdir -p .auto-shutdown

# Create the command-line script for setting the idle timeout
cat > .auto-shutdown/set-time-interval.sh << EOF
#!/opt/conda/bin/python
import json
import requests
TIMEOUT=${TIMEOUT_IN_MINS}
session = requests.Session()
# Getting the xsrf token first from Jupyter Server
response = session.get("http://localhost:8888/jupyter/default/tree")
# calls the idle_checker extension's interface to set the timeout value
response = session.post("http://localhost:8888/jupyter/default/sagemaker-studio-autoshutdown/idle_checker",
            json={"idle_time": TIMEOUT, "keep_terminals": False},
            params={"_xsrf": response.headers['Set-Cookie'].split(";")[0].split("=")[1]})
if response.status_code == 200:
    print("Succeeded, idle timeout set to {} minutes".format(TIMEOUT))
else:
    print("Error!")
    print(response.status_code)
EOF
chmod +x .auto-shutdown/set-time-interval.sh

# "wget" is not part of the base Jupyter Server image, you need to install it first if needed to download the tarball
sudo yum install -y wget
# You can download the tarball from GitHub or alternatively, if you're using VPCOnly mode, you can host on S3
wget -O .auto-shutdown/extension.tar.gz https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/raw/main/sagemaker_studio_autoshutdown-0.1.5.tar.gz

# Or instead, could serve the tarball from an S3 bucket in which case "wget" would not be needed:
# aws s3 --endpoint-url [S3 Interface Endpoint] cp s3://[tarball location] .auto-shutdown/extension.tar.gz

# Installs the extension
cd .auto-shutdown
tar xzf extension.tar.gz
cd sagemaker_studio_autoshutdown-0.1.5

# Activate studio environment just for installing extension
export AWS_SAGEMAKER_JUPYTERSERVER_IMAGE="${AWS_SAGEMAKER_JUPYTERSERVER_IMAGE:-'jupyter-server'}"
if [ "$AWS_SAGEMAKER_JUPYTERSERVER_IMAGE" = "jupyter-server-3" ] ; then
    eval "$(conda shell.bash hook)"
    conda activate studio
fi;
pip install --no-dependencies --no-build-isolation -e .
jupyter serverextension enable --py sagemaker_studio_autoshutdown
if [ "$AWS_SAGEMAKER_JUPYTERSERVER_IMAGE" = "jupyter-server-3" ] ; then
    conda deactivate
fi;

# Restarts the jupyter server
nohup supervisorctl -c /etc/supervisor/conf.d/supervisord.conf restart jupyterlabserver

# Waiting for 30 seconds to make sure the Jupyter Server is up and running
sleep 30

# Calling the script to set the idle-timeout and active the extension
/home/sagemaker-user/.auto-shutdown/set-time-interval.sh
```

I know for several cases what user, what time, and what KernelGateway apps this happened for, but I have not been able to find corresponding logs in Cloudwatch that include the messages that the lifecycle extension prints out, even for cases where I assume the extension has been working.   Should I have log streams under the group `/aws/sagemaker/studio` for each user's lifecycle scripts?  Or are there other places I should be looking?

**Comment by durgasury** [comment]
Hi, do you have any additional extensions along with the studio autoshutdown extension?
If your users restart the jupyter server, it's possible that the idle checker will stop polling for apps (see the [readme here](https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples/tree/main/scripts/install-autoshutdown-server-extension)).

Regarding logs, the LCC log stream will be under `/aws/sagemaker/studio/<domain>/<user>/JupyterServer/default/LifecycleConfigOnStart`. If the extension works as expected, you should see outputs like ` Running App name is ` or `comparing idle time..` if there are notebooks running, in the `/aws/sagemaker/studio/<domain>/<user>/JupyterServer/default` log stream.

**Comment by wdwatkins** [comment]
I haven't added any other extensions in the LifecycleConfig, although its possible users have tried installing plugins within a session.  

Good to know about the potential issues with timing, I will have to dig into that more.  I don't have any log streams below the level of `/aws/sagemaker/studio/<domain>/<user>/JupyterServer/default/`, which seems to suggest the Lifecycle script isn't actually running.

**Comment by cj-dainius-prakapavicius** [comment]
@durgasury 
> If your users restart the jupyter server, it's possible that the idle checker will stop polling for apps (see the [readme here](https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples/tree/main/scripts/install-autoshutdown-server-extension)).

Does this mean that if me or someone else restarts the JupyterServer, auto-shutdown capabilities are gone?

**Comment by wdwatkins** [comment]
Found the issue—either through user error or one of the Sagemaker updates in the last year or so, the lifecycle was not set as a default for all users.  I see the LifeCycleConfig log streams now.

Thanks for your help.
