### ISSUE TITLE
Sagemaker Studio auto shutdown extension not working with restrictive IAM policy

### ISSUE THREAD

**Issue by khanna-vijay** [aws-samples/sagemaker-studio-auto-shutdown-extension#5]
This Extension works only when we give the IAM role of SageMakerAdmin, which is too open for a production. Could you please help to make it work with a restricted policy, and share the minimum IAM permissions required to make this work.

**Comment by rthamman** [comment]
Hi Vijay, we are checking. Will circle back.

**Comment by rthamman** [comment]
Vijay, I believe Andras reached out to you and this has been resolved. IAM permission has no implication on the extension. Let us know otherwise.

**Comment by garzoand** [comment]
I am closing this issue as we were not able to reproduce. However, IAM permission should have no impact, I agree. If you will encounter with the same issue, please feel free to reopen.
