### ISSUE TITLE
Doesn't work in in the current version of Sagemaker which defaults to JupyterLab 4 

### ISSUE THREAD

**Issue by ryaudio** [aws-samples/sagemaker-studio-auto-shutdown-extension#52]
This doesn't appear to work with the new version of Sagemaker which defaults to JupyterLab, and JupyterLab version 4 at that?

What is the recommended method to achieve auto-shutdown for this new Sagemaker experience?

**Comment by MounirHader** [comment]
I have the same question, we are currently migrating from Classic to Studio. It seems with the new Studio architecture we no longer have the JupyterServer <> KernelGateway relationship to achieve the previous auto-shutdown functionality.

**Comment by durgasury** [comment]
Hi, please refer to this sample for the new version of Studio - https://github.com/aws-samples/sagemaker-studio-jupyterlab-lifecycle-config-examples/tree/main/scripts/auto-stop-idle

**Comment by maslick** [comment]
@durgasury  Here's the correct link https://github.com/aws-samples/sagemaker-studio-apps-lifecycle-config-examples/blob/main/jupyterlab/auto-stop-idle/README.md
